import { computed } from 'vue'

type UiTextValue = string | ((params?: Record<string, any>) => string)

const strings: Record<'pt' | 'en', Record<string, UiTextValue>> = {
  pt: {
    searchResultsTitle: 'Resultados da busca',
    searchResultsSubtitle: 'Revise as mensagens e vá direto ao momento certo.',
    loading: 'Carregando...',
    searchingMessages: 'Buscando mensagens…',
    noResults: 'Nenhum resultado encontrado',
    noResultsHint: 'Tente uma busca mais curta ou revise a ortografia.',
    resultsCount: ({ count = 0 } = {}) => `${count} resultado${count === 1 ? '' : 's'}`,
    jumpToDate: 'Ir para a data',
    jumpToDateTitle: 'Ir para a data',
    jumpToDateSubtitle: 'Escolha um dia para ir direto a esse ponto da conversa.',
    preparingTimeline: 'Preparando linha do tempo…',
    calendarLoadError: 'Falha ao carregar o calendário. Tente novamente.',
    monthNavTip: 'Dica: use os controles do mês para navegar rapidamente.',
    previousMonth: 'Mês anterior',
    nextMonth: 'Próximo mês',
    today: 'Hoje',
    noMessagesMonth: 'Sem mensagens neste mês',
    noMessagesHint: 'Tente outro mês ou vá para hoje.',
    chatSettingsTitle: 'Configurações do chat',
    chatNameLabel: 'Nome do chat',
    activeAuthorLabel: 'Autor ativo',
    pageSizeLabel: 'Tamanho da página',
    pageSizeInvalid: 'O tamanho da página deve ser entre 1 e 2000',
    dateFormatLocaleLabel: 'Formato de data e localidade',
    dateFormatLocaleHelp: 'Altera como datas e horários são exibidos no aplicativo.',
    openMediaGallery: 'Abrir galeria de mídia',
    deleteChat: 'Excluir chat',
    deleteChatTitle: 'Excluir chat',
    deleteChatConfirmLead: 'Tem certeza que deseja excluir este chat?',
    deleteChatConfirmBody: 'Isso removerá todos os arquivos e mensagens permanentemente.',
    deleteChatConfirmWarning: 'Essa ação não pode ser desfeita.',
    chatSummaryMessages: ({ count = 0 } = {}) => `${count} mensagem${count === 1 ? '' : 'ens'}`,
    cancel: 'Cancelar',
    saveChanges: 'Salvar alterações',
    deleteNow: 'Excluir agora',
    importExport: 'Importar/Exportar',
    importExportTitle: 'Importar ou exportar',
    failedToImport: 'Falha ao importar',
    getEntireChat: 'Baixar conversa completa',
    actionsApplyCurrentChat: 'Essas ações se aplicam ao chat atual.',
    importMessagesToChat: 'Importar mensagens para este chat',
    upload: 'Enviar',
    close: 'Fechar',
    changeAvatarAria: 'Alterar avatar',
    updateAvatarTitle: 'Atualizar avatar',
    selectProfileImageAria: 'Selecionar imagem de perfil',
    jpgOnlyHint: 'Somente JPG. Imagens quadradas ficam melhores.',
    galleryTitle: 'Galeria',
    filterAll: 'Tudo',
    filterVideo: 'Vídeos',
    filterImage: 'Imagens',
    filterDocuments: 'Documentos',
    filterAudio: 'Áudios',
    loadMoreMessages: 'Carregar mais mensagens',
    messagesCount: ({ count = 0 } = {}) => `${count} mensagem${count === 1 ? '' : 'ens'}`,
    lastMessageSent: 'última mensagem enviada:',
    createNewChat: 'Criar novo chat',
    executeDiskImport: 'Importar do disco',
    executeChatExport: 'Exportar chat',
    enableBlur: 'Ativar desfoque',
    disableBlur: 'Desativar desfoque',
    searchPlaceholder: 'Buscar mensagens...',
    openCalendarTitle: 'Abrir calendário',
    openCalendarAria: 'Abrir calendário',
    profilePhotoAlt: 'Foto de perfil',
    newChatNameLabel: 'Dê um nome para este chat',
    newChatNamePlaceholder: 'Nome do chat',
    importNewChatLabel: 'Importar um novo chat',
    uploadButton: 'Enviar',
    cancelButton: 'Cancelar',
    fileImporterExporter: 'Importador/exportador de arquivos',
    searchHintClose: 'Pressione Esc ou clique fora para fechar.',
    download: 'Baixar',
  },
  en: {
    searchResultsTitle: 'Search Results',
    searchResultsSubtitle: 'Review matches and jump to the right moment.',
    loading: 'Loading...',
    searchingMessages: 'Searching messages…',
    noResults: 'No results found',
    noResultsHint: 'Try a shorter query or check spelling.',
    resultsCount: ({ count = 0 } = {}) => `${count} result${count === 1 ? '' : 's'}`,
    jumpToDate: 'Jump to date',
    jumpToDateTitle: 'Jump to date',
    jumpToDateSubtitle: 'Choose a day to jump directly to that point in the chat.',
    preparingTimeline: 'Preparing timeline…',
    calendarLoadError: 'Failed to load calendar data. Please try again.',
    monthNavTip: 'Tip: Use the month controls to navigate quickly.',
    previousMonth: 'Previous month',
    nextMonth: 'Next month',
    today: 'Today',
    noMessagesMonth: 'No messages this month',
    noMessagesHint: 'Try another month or jump to today.',
    chatSettingsTitle: 'Chat settings',
    chatNameLabel: 'Chat name',
    activeAuthorLabel: 'Active author',
    pageSizeLabel: 'Page size',
    pageSizeInvalid: 'Page size must be a value between 1 and 2000',
    dateFormatLocaleLabel: 'Date format & locale',
    dateFormatLocaleHelp: 'Changes how dates and times are displayed throughout the app.',
    openMediaGallery: 'Open media gallery',
    deleteChat: 'Delete chat',
    deleteChatTitle: 'Delete chat',
    deleteChatConfirmLead: 'Are you sure you want to delete this chat?',
    deleteChatConfirmBody: 'This will remove all assets and messages permanently.',
    deleteChatConfirmWarning: 'You cannot undo this action.',
    chatSummaryMessages: ({ count = 0 } = {}) => `${count} message${count === 1 ? '' : 's'}`,
    cancel: 'Cancel',
    saveChanges: 'Save changes',
    deleteNow: 'Delete now',
    importExport: 'Import/Export',
    importExportTitle: 'Import or export',
    failedToImport: 'Failed to import',
    getEntireChat: 'Get the entire chat',
    actionsApplyCurrentChat: 'These actions apply to the current chat.',
    importMessagesToChat: 'Import messages to this chat',
    upload: 'Upload',
    close: 'Close',
    changeAvatarAria: 'Change avatar',
    updateAvatarTitle: 'Update avatar',
    selectProfileImageAria: 'Select a profile image',
    jpgOnlyHint: 'JPG only. Square images look best.',
    galleryTitle: 'Gallery',
    filterAll: 'All',
    filterVideo: 'Video files',
    filterImage: 'Image files',
    filterDocuments: 'Documents',
    filterAudio: 'Audio files',
    loadMoreMessages: 'Load more messages',
    messagesCount: ({ count = 0 } = {}) => `${count} message${count === 1 ? '' : 's'}`,
    lastMessageSent: 'last message sent:',
    createNewChat: 'Create new chat',
    executeDiskImport: 'Execute disk import',
    executeChatExport: 'Execute chat export',
    enableBlur: 'Enable blur',
    disableBlur: 'Disable blur',
    searchPlaceholder: 'Search messages...',
    openCalendarTitle: 'Open calendar',
    openCalendarAria: 'Open calendar',
    profilePhotoAlt: 'Profile photo',
    newChatNameLabel: 'Give this chat a name',
    newChatNamePlaceholder: 'Chat name',
    importNewChatLabel: 'Import a new chat',
    uploadButton: 'Upload',
    cancelButton: 'Cancel',
    fileImporterExporter: 'File importer/exporter',
    searchHintClose: 'Press Esc or click outside to close.',
    download: 'Download',
  },
}

export const useUiText = () => {
  const uiLocale = computed(() => {
    if (process.client) {
      return navigator.language || 'pt-BR'
    }
    return 'pt-BR'
  })

  const language = computed<'pt' | 'en'>(() => (uiLocale.value.toLowerCase().startsWith('pt') ? 'pt' : 'en'))

  const t = (key: string, params?: Record<string, any>): string => {
    const value = strings[language.value][key]
    if (typeof value === 'function') {
      return value(params)
    }
    return value ?? key
  }

  return {
    t,
    uiLocale,
  }
}
