services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=chatvault'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=usr_chatvault'
    ports:
      - '5432:5432'
  adminer:
    image: adminer
    ports:
      - 8081:8080