services:
  database:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=chatvault'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=usr_chatvault'
    ports:
      - '5432:5432'
  adminer:
    image: adminer
    ports:
      - 8081:8080
  chatvault:
    build: ./
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/chatvault
      - SPRING_DATASOURCE_USERNAME=usr_chatvault
      - SPRING_DATASOURCE_PASSWORD=secret
      - CHATVAULT_MSGPARSER_DATEFORMAT="dd/MM/yyyy HH:mm"
      - CHATVAULT_BUCKET_ROOT=/archive
      - CHATVAULT_BUCKET_IMPORT=/import
      - CHATVAULT_BUCKET_EXPORT=/export
    ports:
      - 8080:8080
    volumes:
      - '/opt/chatvault:/opt/chatvault'
      - './config:/config'
    depends_on:
      - database